var GAME_LEVELS = [
  ["                                                                                  ",
   "                                                                                  ",
   "                                                                                  ",
   "                                          o                                       ",
   "                                        oxxxx                                     ",
   "                                        xxxxxx                               x    ",
   "  x                                   oxxxxxxxxo                             x    ",
   "  x@                                  xxxxxxxxxx                             x    ",
   "  xx                                oxxxxxxxxxxxxo                          #x    ",
   "  xxx                               xxxxxxxxxxxxxx$           ox            xx    ",
   "  xxxx       o                    oxxxxxxxxxxxxxxxxo          xx        oxxxxx    ",
   "  xxxxx      x                    xxxxxxxxxxxxxxxxxx         xxx       xxxxxxx    ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx!!!!xxxxxxxxx    ",
   "                             x!!!x                  x     x                       ",
   "                             xxxxx                  x!!!!!x                       ",
   "                                                    xxxxxxx                       ",
   "                                                                                  ",
   "                                                                                  ",
   "                                                                                  "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "              xxxx!!!!                 x          xxxxxxxx           !xxxxxxxxxxxxx                xx!!!!!!!!!          ",
   "              xxxxvvvv                 x          xxxxxxxx           v            x                x !!!!!!!!v          ",
   "              xxxx                     x          xxxxxxxx                        x                x !!!!!!!            ",
   "     xx      xxxxx                     x                 x                        x                x !!!!!!             ",
   "    xxx      xxxxx                     x                 x                        x                x !!!!!              ",
   " @xxxxx      xxxxx                     x          o  o   x                                         x !!!                ",
   "xxxxxxx     xxxxxx xx  xxxxxxxxxxxxxxxxx       xxxx  x   x                o                        x !!                 ",
   "xxxxxxx     xxxxxx     xxxxxxxxxxxxxxx       oxxxxx  x   x          o$ xxxx  xxx                   x !                  ",
   "xxxxxxx     xxxxxx     xxxxxxxxxxxxxx        xxxxxx  x   x         xxx                             x v                  ",
   "xxxxxxx     xxxxxx     xxxxxxxxxxxxx       oxxxxxxx  x   x                      oxxxxx             x                    ",
   "xxxxxxx     xxxxxx     xxxxxxxxxxxx        xxxxxxxx  x   x                      xxxxxxx            x                    ",
   "xxxxxxx     xxxxxx!!!!!!!!!!!!!!!!       oxxxxxxxxx  x   x                    oxxxxxxxxxo          x                    ",
   "xxxxxxx      x!!!!!!!!!!!!!!!!!!!v     oxxxxxxxxxxx  x   x                    xxxxxxxxxxx          x                    ",
   "xxxxxxx  xxo  x!!!!!!!!!!xxxxxxxx     xxxxxxxxxxxxx  x   xxx!!!!xxxxxxxx    oxxxxxxxxxxxxxo        x                    ",
   "xxxxxx!!!!!x   xxxxxxxxxxxxxxxxxx   oxxxxxxxxxxxxxx  x     x!!!!!!!xx       xxxxxxxxxxxxxxx        x                    ",
   "xxxxxx!!!!!xx                       xxxxxxxxxxxxxxx                        xxxxxxxxxxxxxxxxxo                           ",
   "xxxxxxxxxxxxx               o                              o            o                           o         o    #    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["  x                                                                  x!!!!!!!!!!v!!!!!!!!v!!!!!!!!!v!!!!!!!!!v",
   "  x                                                                  x                                        ",
   "  x                                          x                       x                                        ",
   "  x                                        ox     xxxxxx             x                                        ",
   "  x                                        x                         x                                        ",
   "  x                                       x                          x                                        ",
   "  x                                      x                           x                                        ",
   "  x                                    ox                            x                                        ",
   "  x                                    x                             x                                        ",
   "  x                                   x     xxx                      x                                        ",
   "  x                                  x                               x                                        ",
   "  x                                ox                                x                                        ",
   "  x                                x                                 x                                        ",
   "  x                               x                                  x                                        ",
   "  x                              x        xxx                        x                             !          ",
   "  x                            ox                                    x                             xxx        ",
   "  x                            x                                     x                             x!         ",
   "  x                           x                                      x                             xv         ",
   "  x                          x                                       x                             x          ",
   "  x                         x                                        x                             x          ",
   "  x                       ox                                         x                             x          ",
   "  x                       x           o                              x              x              !          ",
   "  x                      x           xx                              x              x              !          ",
   "  x                     x                                            x              x              !          ",
   "  x                    x                                             x             xx              !          ",
   "  x                  ox                                              x              x    xxx       !          ",
   "  x                  x                                               x      o       x              !          ",
   "  x                 x                                                x    xxxx      x              !          ",
   "  x                x                                                 x              x              !          ",
   "  x               x                                                  x             xx              !          ",
   "  x             ox              xx                                   x              x              !          ",
   "  x             x                                                    x      o       x              !          ",
   "  x            x                                                     x     xxx      x o            !          ",
   "  x           x                                                      x              xxx            !          ",
   "  x          x                                                       x             xx              !          ",
   "  x         x                            !!!!v!!!!!!!v!!!!!!v!!!!!!!!x              x              !          ",
   "  x        x                                                         x              x              !          ",
   "  x      ox                                                          x      o       x              !          ",
   "  x      x                                                           x     xxxx     x              !          ",
   "  x     x                                                                          x                          ",
   "  x    x                                                                        o x                         # ",
   "  x   x                      o                                                   x      xxxxx               x ",
   "  x@ xxx                    xx       $          o               o                x                   o     x  ",
   "  xxxxxx                             xxxxx    xxxxx   xxxxx  xxxxx   xxxx  xxx x                   xxxxx      ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!"],
  ["                                                                                          ",
   "                                                                                          ",
   "                                                                                          ",
   "                                                                                          ",
   "                                                                                          ",
   "                                                                                          ",
   "                                                                                          ",
   "              xx      x x                                                                 ",
   "  x                   x x  xxx x  x    x  x  x  x  xx  x                                  ",
   "  x        xx          x   x x x  x    x x x x   x  x x x                                 ",
   "  x  @                 x   xxx xxxx    xx   xx    x  x  xx                                ",
   "  xxxxxxx                                                                                 ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
